# Generated by Django 2.0.5 on 2018-05-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donatur',
            fields=[
                ('nomor_identitas', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('npwp', models.CharField(max_length=20)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'donatur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualDonor',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'individual_donor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('npm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat_tinggal', models.CharField(max_length=50)),
                ('alamat_domisili', models.CharField(max_length=50)),
                ('nama_bank', models.CharField(max_length=50)),
                ('no_rekening', models.CharField(max_length=20)),
                ('nama_pemilik', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('urutan', models.IntegerField(primary_key=True, serialize=False)),
                ('no_urut_skema_beasiswa_aktif', models.IntegerField()),
                ('tgl_bayar', models.DateField()),
                ('nominal', models.IntegerField()),
            ],
            options={
                'db_table': 'pembayaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('no_urut', models.IntegerField(primary_key=True, serialize=False)),
                ('waktu_daftar', models.DateTimeField()),
                ('status_daftar', models.CharField(max_length=20)),
                ('status_terima', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pendaftaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pengguna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('tanggal', models.DateField(primary_key=True, serialize=False)),
                ('no_urut_skema_beasiswa_aktif', models.IntegerField()),
                ('judul', models.CharField(max_length=20)),
                ('isi', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'pengumuman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatAkademik',
            fields=[
                ('no_urut', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=1)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('jumlah_sks', models.IntegerField()),
                ('ips', models.FloatField()),
                ('lampiran', models.CharField(max_length=50)),
                ('no_rekening', models.CharField(max_length=20)),
                ('nama_pemilik', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'riwayat_akademik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkemaBeasiswa',
            fields=[
                ('kode', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis', models.CharField(max_length=20)),
                ('deskripsi', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'skema_beasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempatWawancara',
            fields=[
                ('kode', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('lokasi', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tempat_wawancara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wawancara',
            fields=[
                ('no_urut_skema_beasiswa_aktif', models.IntegerField(primary_key=True, serialize=False)),
                ('jadwal', models.DateTimeField()),
            ],
            options={
                'db_table': 'wawancara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yayasan',
            fields=[
                ('no_sk_yayasan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('no_telp_cp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'yayasan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main_app.Pengguna')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkemaBeasiswaAktif',
            fields=[
                ('kode_skema_beasiswa', models.ForeignKey(db_column='kode_skema_beasiswa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main_app.SkemaBeasiswa')),
                ('no_urut', models.IntegerField()),
                ('tgl_mulai_pendaftaran', models.DateField()),
                ('tgl_tutup_pendaftaran', models.DateField()),
                ('periode_penerimaan', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('jumlah_pendaftar', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skema_beasiswa_aktif',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyaratBeasiswa',
            fields=[
                ('kode_beasiswa', models.ForeignKey(db_column='kode_beasiswa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main_app.SkemaBeasiswa')),
                ('syarat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'syarat_beasiswa',
                'managed': False,
            },
        ),
    ]
